### ISSUE TITLE
Document Main Components

### ISSUE THREAD

**Issue by Pertempto** [Pertempto/mada#1]
Document the overall structure of the system, including the Mobile App and the Backend.

**Comment by Pertempto** [comment]
@davidlandes, I very briefly documented the main components [here](https://github.com/Pertempto/mada/wiki/Components). I'd appreciate any feedback!

**Comment by DavidLandes** [comment]
@Pertempto I think it's a great overview! I like how you gave example requests on the mobile app side, I can see how useful this could be!
